let ccDiscoveryResults=[];
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function liveCard(l,i){return `<div class="lead"><span class="score">${esc(l.score)}</span><h4>${esc(l.business)}</h4><p>${esc(l.industry)} · ${esc(l.city)}, ${esc(l.state)}</p><div class="meta"><span>PHONE<b>${esc(l.phone||'Not public')}</b></span><span>EMAIL<b>${esc(l.email||'Not public')}</b></span><span>WEBSITE<b>${l.website?`<a href="${esc(l.website)}" target="_blank" rel="noopener" style="color:#74ebd1">Visit</a>`:'Not public'}</b></span><span>REVENUE<b>Unknown</b></span></div><div class="toolbar"><span class="tag">Public record</span><button class="btn hot" onclick="saveDiscovery(${i})">Save Lead</button></div></div>`}
async function runFind(){
 const out=document.getElementById('results'); if(!out)return;
 if(mode==='demo'){out.innerHTML='<div class="empty"><b>Discovering demo businesses…</b>Filtering sample records.</div>';setTimeout(()=>{let a=demoLeads.filter(x=>x.industry.toLowerCase().includes(document.getElementById('industry').value.toLowerCase()));out.innerHTML=a.length?`<h3>${a.length} demo opportunities</h3><div class="leadgrid">${a.map(card).join('')}</div>`:'<div class="empty"><b>No demo matches</b>Try another industry.</div>'},350);return;}
 const m=document.getElementById('market').value.trim(),ind=document.getElementById('industry').value.trim();
 if(!m||!ind){out.innerHTML='<div class="empty"><b>Market and industry required</b>Enter both fields and search again.</div>';return;}
 out.innerHTML='<div class="empty"><b>Searching live public business records…</b>Locating market → discovering businesses → ranking contact completeness</div>';
 try{const r=await fetch(`/api/leads?market=${encodeURIComponent(m)}&industry=${encodeURIComponent(ind)}`);const data=await r.json();if(!r.ok)throw new Error(data.error||'Discovery failed');ccDiscoveryResults=data.leads||[];out.innerHTML=ccDiscoveryResults.length?`<h3>${ccDiscoveryResults.length} live businesses found</h3><p>Real public business records. Unknown financial/credit fields stay Unknown until verified.</p><div class="leadgrid">${ccDiscoveryResults.map(liveCard).join('')}</div>`:'<div class="empty"><b>No public matches found</b>Try a broader industry term or nearby market.</div>';}catch(e){out.innerHTML=`<div class="empty"><b>Live discovery could not complete</b>${esc(e.message)}. Try again in a moment.</div>`;}
}
function saveDiscovery(i){if(mode!=='live')return;const l=ccDiscoveryResults[i];if(!l)return;let a=liveLeads();if(a.some(x=>x.business===l.business&&x.phone===l.phone)){alert('This lead is already saved.');return;}a.push({...l,id:Date.now()+i});save(a);alert(`${l.business} saved to Live Leads.`)}