let ccDiscoveryResults=[];
let ccSelected=new Set();
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function liveCard(l,i){const checked=ccSelected.has(i)?'checked':'';return `<div class="lead" style="position:relative"><label style="display:flex;gap:7px;align-items:center;margin-bottom:10px;color:#aab6c7;font-size:10px"><input type="checkbox" class="ccpick" data-i="${i}" ${checked} onchange="toggleDiscovery(${i},this.checked)"> Select</label><span class="score">${esc(l.score)}</span><h4>${esc(l.business)}</h4><p>${esc(l.industry)} · ${esc(l.city)}, ${esc(l.state)}</p><div style="margin:12px 0;padding:11px;background:#0a111a;border:1px solid #ffffff0d;border-radius:10px"><div style="font-size:8px;color:#657287;margin-bottom:8px">CONTACT INFORMATION</div><div style="font-size:11px;color:#dce5f2;margin-bottom:7px">☎ ${esc(l.phone||'No public phone')}</div><div style="font-size:11px;color:#dce5f2;word-break:break-all">✉ ${esc(l.email||'No public email')}</div></div><div class="meta"><span>WEBSITE<b>${l.website?`<a href="${esc(l.website)}" target="_blank" rel="noopener" style="color:#74ebd1">${esc(l.website.replace(/^https?:\/\//,'').replace(/\/$/,''))}</a>`:'Not public'}</b></span><span>EST. REVENUE<b>Unknown</b></span></div><div class="toolbar"><span class="tag">Public record</span><button class="btn hot" onclick="saveDiscovery(${i})">Save Lead</button></div></div>`}
function selectionBar(){return `<div class="toolbar" style="position:sticky;top:0;z-index:5;background:#0d131df2;padding:10px 0"><label class="btn" style="display:flex;align-items:center;gap:7px"><input id="ccAll" type="checkbox" onchange="selectAllDiscovery(this.checked)"> Select All</label><span id="ccSelCount" class="tag">0 selected</span><button class="btn hot" onclick="saveSelectedDiscovery()">Save Selected</button><button class="btn" onclick="makeDiscoveryList()">Make List</button><button class="btn" onclick="exportDiscoveryCSV()">Download / Export CSV</button></div>`}
function renderDiscovery(){const out=document.getElementById('results');if(!out)return;out.innerHTML=ccDiscoveryResults.length?`<h3>${ccDiscoveryResults.length} live businesses found</h3><p>Phone and email are shown up front when publicly available. Select any results to save, make a reusable list, or export.</p>${selectionBar()}<div class="leadgrid">${ccDiscoveryResults.map(liveCard).join('')}</div>`:'<div class="empty"><b>No public matches found</b>Try a broader industry term or nearby market.</div>';updateSelectionUI()}
function toggleDiscovery(i,on){on?ccSelected.add(i):ccSelected.delete(i);updateSelectionUI()}
function selectAllDiscovery(on){ccSelected.clear();if(on)ccDiscoveryResults.forEach((_,i)=>ccSelected.add(i));document.querySelectorAll('.ccpick').forEach(x=>x.checked=on);updateSelectionUI()}
function updateSelectionUI(){const c=document.getElementById('ccSelCount');if(c)c.textContent=`${ccSelected.size} selected`;const a=document.getElementById('ccAll');if(a){a.checked=ccDiscoveryResults.length>0&&ccSelected.size===ccDiscoveryResults.length;a.indeterminate=ccSelected.size>0&&ccSelected.size<ccDiscoveryResults.length}}
function picked(){return [...ccSelected].sort((a,b)=>a-b).map(i=>ccDiscoveryResults[i]).filter(Boolean)}
function mergeIntoLeads(items){let a=liveLeads(),added=0;items.forEach((l,i)=>{if(!a.some(x=>x.business===l.business&&x.phone===l.phone&&x.email===l.email)){a.push({...l,id:Date.now()+i,status:l.status||'New'});added++}});save(a);return added}
function saveSelectedDiscovery(){const items=picked();if(!items.length)return alert('Select at least one lead first.');const n=mergeIntoLeads(items);alert(`${n} lead${n===1?'':'s'} saved to Live Leads.`)}
function makeDiscoveryList(){const items=picked();if(!items.length)return alert('Select at least one lead first.');const name=prompt('Name this list',`${document.getElementById('industry')?.value||'Lead'} Prospects`);if(!name)return;const lists=JSON.parse(localStorage.getItem('cc_saved_lists')||'[]');lists.push({id:Date.now(),name,created:new Date().toISOString(),leads:items});localStorage.setItem('cc_saved_lists',JSON.stringify(lists));mergeIntoLeads(items);alert(`List “${name}” saved with ${items.length} leads.`)}
function exportRows(items){const h=['Phone Number','First Name','Last Name','Business Name','TIB','Email','Industry','City','State','ZIP','Website','Estimated Revenue','FICO','Funding Need','Urgency','Existing Debt','Source','Lead Score','Status','Last Contacted','Email Status','Notes'];const rows=items.map(l=>[l.phone||'',l.first||'',l.last||'',l.business||'',l.tib||'Unknown',l.email||'',l.industry||'',l.city||'',l.state||'',l.zip||'',l.website||'',l.revenue||'Unknown',l.fico||'Unknown',l.fundingNeed||'Unknown',l.urgency||'Unknown',l.debt||'Unknown',l.source||'Public discovery',l.score||0,l.status||'New','','','']);return [h,...rows].map(r=>r.map(v=>'"'+String(v??'').replaceAll('"','""')+'"').join(',')).join('\n')}
function exportDiscoveryCSV(){const items=picked();if(!items.length)return alert('Select at least one lead first.');const csv=exportRows(items),u=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'})),a=document.createElement('a');a.href=u;a.download=`croce-capital-${(document.getElementById('industry')?.value||'leads').toLowerCase().replace(/[^a-z0-9]+/g,'-')}.csv`;document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(u)}
async function runFind(){
 const out=document.getElementById('results'); if(!out)return;
 ccSelected.clear();
 if(mode==='demo'){out.innerHTML='<div class="empty"><b>Discovering demo businesses…</b>Filtering sample records.</div>';setTimeout(()=>{let a=demoLeads.filter(x=>x.industry.toLowerCase().includes(document.getElementById('industry').value.toLowerCase()));ccDiscoveryResults=a;renderDiscovery()},350);return;}
 const m=document.getElementById('market').value.trim(),ind=document.getElementById('industry').value.trim();
 if(!m||!ind){out.innerHTML='<div class="empty"><b>Market and industry required</b>Enter both fields and search again.</div>';return;}
 out.innerHTML='<div class="empty"><b>Searching live public business records…</b>Locating market → discovering businesses → ranking contact completeness</div>';
 try{const r=await fetch(`/api/leads?market=${encodeURIComponent(m)}&industry=${encodeURIComponent(ind)}`);const data=await r.json();if(!r.ok)throw new Error(data.error||'Discovery failed');ccDiscoveryResults=data.leads||[];renderDiscovery();}catch(e){out.innerHTML=`<div class="empty"><b>Live discovery could not complete</b>${esc(e.message)}. Try again in a moment.</div>`;}
}
function saveDiscovery(i){if(mode!=='live')return;const l=ccDiscoveryResults[i];if(!l)return;const n=mergeIntoLeads([l]);alert(n?`${l.business} saved to Live Leads.`:'This lead is already saved.')}
