const UA='CroceCapital/1.1 public-business-enrichment';
const json=(res,status,body)=>{res.statusCode=status;res.setHeader('Content-Type','application/json');res.setHeader('Cache-Control','s-maxage=300, stale-while-revalidate=600');res.end(JSON.stringify(body));};
const clean=s=>String(s||'').trim();
function score(t){let s=45;if(t.phone)s+=18;if(t.website)s+=14;if(t.email)s+=14;if(t.decisionMakers?.length)s+=8;return Math.min(99,s)}
function categoryRegex(q){q=String(q||'').toLowerCase();const map={hvac:'hvac|heating|air_conditioning|air conditioning',roofing:'roof|roofer',plumbing:'plumb|plumber',construction:'construction|contractor|builder|concrete',electrician:'electric|electrician',landscaping:'landscap|lawn|garden',restaurant:'restaurant|fast_food|cafe'};return map[q]||q.replace(/[^a-z0-9 _-]/g,'').replace(/\s+/g,'.*')||'.*'}
const abs=(base,p)=>{try{return new URL(p,base).href}catch{return''}};
async function getPage(url){try{const r=await fetch(url,{headers:{'User-Agent':UA,'Accept':'text/html'},redirect:'follow',signal:AbortSignal.timeout(4500)});if(!r.ok)return'';return (await r.text()).slice(0,350000)}catch{return''}}
function extract(html,base){const emails=[...new Set((html.match(/[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}/gi)||[]).filter(x=>!x.match(/example\.|sentry|wixpress|wordpress/i)))];const phones=[...new Set((html.match(/(?:\+?1[\s.-]?)?\(?\d{3}\)?[\s.-]\d{3}[\s.-]\d{4}/g)||[]))];const links=[...html.matchAll(/href=["']([^"']+)["']/gi)].map(x=>x[1]);const linkedin=links.find(x=>/linkedin\.com\/(in|company)\//i.test(x));return {email:emails[0]||'',phone:phones[0]||'',linkedin:linkedin?abs(base,linkedin):''}}
function people(html){const text=html.replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ').replace(/&nbsp;|&amp;/g,' ').replace(/\s+/g,' ');const roles='Owner|Founder|Co-Founder|CEO|Chief Executive Officer|President|Managing Partner|Managing Director|General Manager';const re=new RegExp(`([A-Z][a-z]+(?:\\s+[A-Z][a-z]+){1,2})\\s*[-–|,]?\\s*(${roles})|(${roles})\\s*[-–|,:]?\\s*([A-Z][a-z]+(?:\\s+[A-Z][a-z]+){1,2})`,'g');const out=[];let m;while((m=re.exec(text))&&out.length<3){const name=m[1]||m[4],role=m[2]||m[3];if(name&&role&&!out.some(x=>x.name===name))out.push({name,role,profile:''})}return out}
async function enrich(lead){if(!lead.website)return lead;let base=lead.website;if(!/^https?:\/\//i.test(base))base='https://'+base;const home=await getPage(base);if(!home)return lead;let data=extract(home,base),makers=people(home);const candidates=[...home.matchAll(/href=["']([^"']*(?:contact|about|team|leadership|company|staff)[^"']*)["']/gi)].map(x=>abs(base,x[1])).filter(Boolean).slice(0,3);for(const u of [...new Set(candidates)]){const h=await getPage(u);if(!h)continue;const d=extract(h,u);if(!data.email&&d.email)data.email=d.email;if(!data.phone&&d.phone)data.phone=d.phone;if(!data.linkedin&&d.linkedin)data.linkedin=d.linkedin;makers=[...makers,...people(h)].filter((x,i,a)=>a.findIndex(y=>y.name===x.name)===i).slice(0,3)}return {...lead,email:lead.email||data.email,phone:lead.phone||data.phone,linkedin:data.linkedin||'',decisionMakers:makers,enriched:!!(data.email||data.phone||makers.length),website:base}}
export default async function handler(req,res){if(req.method!=='GET')return json(res,405,{error:'GET only'});const market=clean(req.query.market)||'Louisville, KY',industry=clean(req.query.industry)||'HVAC';try{const gr=await fetch('https://nominatim.openstreetmap.org/search?format=json&limit=1&countrycodes=us&q='+encodeURIComponent(market),{headers:{'User-Agent':UA,'Accept-Language':'en'}});if(!gr.ok)throw new Error('Location lookup failed');const gj=await gr.json();if(!gj[0])return json(res,404,{error:'Market not found'});const lat=Number(gj[0].lat),lon=Number(gj[0].lon),rx=categoryRegex(industry);const q=`[out:json][timeout:20];(nwr(around:30000,${lat},${lon})[name][office~"${rx}",i];nwr(around:30000,${lat},${lon})[name][craft~"${rx}",i];nwr(around:30000,${lat},${lon})[name][shop~"${rx}",i];nwr(around:30000,${lat},${lon})[name][amenity~"${rx}",i];nwr(around:30000,${lat},${lon})[name][description~"${rx}",i];);out center tags 60;`;const or=await fetch('https://overpass-api.de/api/interpreter',{method:'POST',headers:{'User-Agent':UA,'Content-Type':'application/x-www-form-urlencoded'},body:'data='+encodeURIComponent(q)});if(!or.ok)throw new Error('Public business source unavailable');const oj=await or.json(),seen=new Set(),raw=[];for(const e of oj.elements||[]){const t=e.tags||{},name=clean(t.name);if(!name||seen.has(name.toLowerCase()))continue;seen.add(name.toLowerCase());raw.push({id:'osm-'+e.type+'-'+e.id,business:name,first:'',last:'',industry,city:clean(t['addr:city'])||market.split(',')[0],state:clean(t['addr:state'])||clean(market.split(',')[1]),zip:clean(t['addr:postcode']),phone:clean(t.phone||t['contact:phone']),email:clean(t.email||t['contact:email']),website:clean(t.website||t['contact:website']),tib:'Unknown',revenue:'Unknown',fico:'Unknown',fundingNeed:'Unknown',urgency:'Unknown',debt:'Unknown',status:'New',source:'Public business data'});if(raw.length>=30)break}const leads=[];for(let i=0;i<raw.length;i+=5){const batch=await Promise.all(raw.slice(i,i+5).map(enrich));leads.push(...batch)}leads.forEach(l=>l.score=score(l));leads.sort((a,b)=>(!!b.phone+!!b.email+(b.decisionMakers?.length?1:0))-(!!a.phone+!!a.email+(a.decisionMakers?.length?1:0))||b.score-a.score);return json(res,200,{market,industry,count:leads.length,leads,notice:'Enriched from publicly available company websites. Private contact details are not inferred.'})}catch(e){return json(res,502,{error:e.message||'Discovery failed'})}}
